/* tslint:disable */
/* eslint-disable */
/**
 * GraphScope FLEX HTTP SERVICE API
 * This is a specification for GraphScope FLEX HTTP service based on the OpenAPI 3.0 specification. You can find out more details about specification at [doc](https://swagger.io/specification/v3/).  Some useful links: - [GraphScope Repository](https://github.com/alibaba/GraphScope) - [The Source API definition for GraphScope Interactive](https://github.com/GraphScope/portal/tree/main/httpservice)
 *
 * OpenAPI spec version: 0.9.1
 * Contact: graphscope@alibaba-inc.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DataSourcePropertyMapping } from './data-source-property-mapping';
import { DataSourceSourceVertexMapping } from './data-source-source-vertex-mapping';

/**
 *
 *
 * @export
 * @interface DataSource
 */
export interface DataSource {
  /**
   * @type {string}
   * @memberof DataSource
   */
  dataSourceType?: DataSourceDataSourceTypeEnum;

  /**
   * @type {string}
   * @memberof DataSource
   */
  typeName?: string;

  /**
   * edge only
   *
   * @type {string}
   * @memberof DataSource
   */
  sourceVertexType?: string;

  /**
   * edge only
   *
   * @type {string}
   * @memberof DataSource
   */
  destinationVertexType?: string;

  /**
   * @type {string}
   * @memberof DataSource
   */
  location?: string;

  /**
   * @type {DataSourceSourceVertexMapping}
   * @memberof DataSource
   */
  sourceVertexMapping?: DataSourceSourceVertexMapping;

  /**
   * @type {DataSourceSourceVertexMapping}
   * @memberof DataSource
   */
  destinationVertexMapping?: DataSourceSourceVertexMapping;

  /**
   * @type {DataSourcePropertyMapping}
   * @memberof DataSource
   */
  propertyMapping?: DataSourcePropertyMapping;
}

/**
 * @export
 * @enum {string}
 */
export enum DataSourceDataSourceTypeEnum {
  LOCALFILE = 'LOCAL_FILE',
  ODPS = 'ODPS',
  OSS = 'OSS',
}
