/* tslint:disable */
/* eslint-disable */
/**
 * GraphScope FLEX HTTP SERVICE API
 * This is a specification for GraphScope FLEX HTTP service based on the OpenAPI 3.0 specification. You can find out more details about specification at [doc](https://swagger.io/specification/v3/).  Some useful links: - [GraphScope Repository](https://github.com/alibaba/GraphScope) - [The Source API definition for GraphScope Interactive](https://github.com/GraphScope/portal/tree/main/httpservice)
 *
 * OpenAPI spec version: 0.9.1
 * Contact: graphscope@alibaba-inc.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { EdgeType } from './edge-type';
import { VertexType } from './vertex-type';

/**
 *
 *
 * @export
 * @interface Schema
 */
export interface Schema {
  /**
   * @type {Array<VertexType>}
   * @memberof Schema
   */
  vertexTypes?: Array<VertexType>;

  /**
   * @type {Array<EdgeType>}
   * @memberof Schema
   */
  edgeTypes?: Array<EdgeType>;
}
