name: Publish npm packages
on:
  pull_request:
    types: [closed]

jobs:
  publish:
    runs-on: ubuntu-latest
    # 当具有 release 标签的 PR 被合并时，自动发布包版本
    if: contains(github.event.pull_request.labels.*.name, 'release') && github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm and dependencies
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true

      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN} & pnpm run publish
